sil21\VitrineBundle\Entity\Brand:
    repositoryClass: sil21\VitrineBundle\Repository\BrandRepository
    type: entity
    table: sil21_brand
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
            column: Name
            nullable: false
            
    oneToMany:
        products:
             targetEntity: Product
             mappedBy: brand
             cascade: [ "persist", "remove" ]

    lifecycleCallbacks: {  }
