sil21\VitrineBundle\Entity\Category:
    repositoryClass: sil21\VitrineBundle\Repository\CategoryRepository
    type: entity
    table: sil21_category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
           type: string
           length: 100
           nullable: false

    oneToMany:
        products:
             targetEntity: Product
             mappedBy: category
             cascade: [ "persist", "remove" ]
