sil21\VitrineBundle\Entity\Client:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: '255'
            nullable: false

        firstname:
            type: string
            length: '255'
            nullable: false

        address:
            type: text
            nullable: false

        tel:
            type: string
            length: '10'

        dateBirthday:
            type: datetime
            
    oneToMany:
        commandes:
             targetEntity: Commande
             mappedBy: client
             cascade: ["persist", "remove"]

    lifecycleCallbacks: {  }
