sil21\VitrineBundle\Entity\LigneCommande:
    type: entity
    table: sil21_lignecommande
    id:
        commande:
            associationKey: trues
        product:
            associationKey: true
          
    fields:
        qte:
            type: integer
            nullable: false

        price:
            type: decimal
            nullable: false
            
    manyToOne:
        product:
             targetEntity: Product
             joinColumn:
                 name: product_id
                 referencedColumnName: id
                 nullable: false
                 
        order:
             targetEntity: Order
             inversedBy: lignecommandes
             joinColumn:
                 name: order_id
                 referencedColumnName: id
                 nullable: false
