sil21\VitrineBundle\Entity\OrderLine:
    type: entity
    table: sil21_order_line
    id:
        order:
            associationKey: true
        product:
            associationKey: true
          
    fields:
        qte:
            type: integer
            nullable: false

        price:
            type: decimal
            scale: 2
            nullable: false
            
    manyToOne:
        product:
             targetEntity: Product
             joinColumn:
                 name: product_id
                 referencedColumnName: id
                 nullable: false
                 
        order:
             targetEntity: Order
             inversedBy: orderlines
             joinColumn:
                 name: order_id
                 referencedColumnName: id
                 nullable: false
