sil21\VitrineBundle\Entity\Order:
    type: entity
    table: sil21_order
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        date:
            type: datetime
            nullable: false
               
        etat:
            type: integer
            nullable: false

    manyToOne:
        client:
            targetEntity: Client
            inversedBy: orders
            joinColumn:
                name: client_id
                referencedColumnName: id

    oneToMany:
            orderlines:
                 targetEntity: OrderLine
                 mappedBy: order
                 cascade: [ "persist", "remove" ]
