
sil21\VitrineBundle\Entity\Product:
    repositoryClass: sil21\VitrineBundle\Repository\ProductRepository
    type: entity
    table: sil21_product                        # La table a laquelle elle correspond
    id:                                   # Les champs qui composent la clé primaire
       id:
           type: integer
           generator: { strategy: AUTO }
           
    fields:                               # Les autres champs de la table
       name:
           type: string
           length: 100
           nullable: false

       image:
                  type: string
                  length: 255

       price:
           type: decimal
           scale: 2
           nullable: false

       stock:
            type: integer
            options:
                default: 0
            nullable: false

       description:
           type: text
           nullable: false
           
    manyToOne:
        category:
             targetEntity: Category
             inversedBy: products
             joinColumn:
                 name: category_id
                 referencedColumnName: id
                 
        brand:
             targetEntity: Brand
             inversedBy: products
             joinColumn:
                 name: brand_id
                 referencedColumnName: id
