# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            anonymous:    true
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                default_target_path: sil21_vitrine_homepage

            logout:
                path: fos_user_security_logout

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # -- Order
        - { path: ^/(fr|en)/order/, role: ROLE_USER }

        # -- Cart
        - { path: ^/(fr|en)/cart/validate, role: ROLE_USER }

        # -- Admin
        - { path: ^/(fr|en)/admin/, role: ROLE_ADMIN }