# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # -- Categorie
        #- { path: ^/category/listUser, role: ROLE_USER }
        #- { path: ^/category/\d+/articles, role: ROLE_USER }
        #- { path: ^/category/, role: ROLE_ADMIN }

        # -- Client
        #- { path: ^/client/, role: ROLE_ADMIN }
        #- { path: ^/profile/, role: ROLE_USER }

        # -- Order
        #- { path: ^/Order/\d+/show, role: ROLE_USER }
        #- { path: ^/Order/listUser, role: ROLE_USER }
        #- { path: ^/Order/, role: ROLE_ADMIN }

        # -- Brand
        #- { path: ^/marque/listUser, role: ROLE_USER }
        #- { path: ^/marque/\d+/articles, role: ROLE_USER }
        #- { path: ^/marque/, role: ROLE_ADMIN }

        # -- Cart
        - { path: ^/cart/validate, role: ROLE_USER }

        # -- Produit
        #- { path: ^/product/listUser, role: ROLE_USER }
        #- { path: ^/product/, role: ROLE_ADMIN }

        - { path: ^/admin/, role: ROLE_ADMIN }