# ---------- IMPORT ----------

# -- Catégorie
sil21_admin_categories:
    resource: "@sil21AdminBundle/Resources/config/routing/category.yml"
    prefix: /category

# -- Produit
sil21_admin_products:
    resource: "@sil21AdminBundle/Resources/config/routing/product.yml"
    prefix: /product

# -- Produit
sil21_admin_marques:
    resource: "@sil21AdminBundle/Resources/config/routing/Marque.yml"
    prefix: /marque

# -- Order
sil21_admin_orders:
        resource: "@sil21AdminBundle/Resources/config/routing/Order.yml"
        prefix:   /order

# -- Client
sil21_client:
    resource: "@sil21AdminBundle/Resources/config/routing/client.yml"
    prefix:   /client