<?php
	
	namespace sil21\VitrineBundle\Repository;
	
	/**
	 * MarqueRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class BrandRepository extends \Doctrine\ORM\EntityRepository {
		/**
		 * @return array
		 */
		public function findAllOrderedByName() {
			$qb = $this->createQueryBuilder( 'l' )
			
			$qb->select( 'l' )
				->join( 'l.emprunts', 'e', 'WITH' )
				->where( $qb->expr()->eq( 'e.livre', ':id' ) )
				->setParameter( 'id', $livre_id );
			
			$qb->getQuery()->getResult()
			
			return $this->getEntityManager()
				    ->createQuery( 'SELECT p FROM sil21VitrineBundle:Brand p ORDER BY p.name' )
				    ->getResult();
		}
		
		public function findAllBetterSales() {
			$stmt = $this->getEntityManager()->getConnection()->prepare(
				'SELECT p.brand_id
				FROM (
					SELECT l.product_id AS id, SUM(l.qte) AS cnt
					FROM sil21_order_line l
					GROUP BY l.product_id
					ORDER BY cnt DESC ) popu
				NATURAL JOIN sil21_product p
				LIMIT 5'
			);
			$stmt->execute();
			$brandIDs = $stmt->fetchAll();
			$brands   = [];
			foreach ( $brandIDs as $id ) {
				$brands[] = $this->getEntityManager()
						 ->getRepository( 'sil21VitrineBundle:Brand' )
						  ->findOneBy( [ 'id' => $id ] );
			}
			
			return $brands;
			
		}
	}
