<?php
	
	namespace sil21\VitrineBundle\Repository;
	
	/**
	 * CategoryRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class CategoryRepository extends \Doctrine\ORM\EntityRepository {
		/**
		 * @return array
		 */
		public function findAllOrderedByName() {
			return $this->getEntityManager()
				    ->createQuery( 'SELECT c FROM sil21VitrineBundle:Category c ORDER BY c.name ASC' )
				    ->getResult();
		}
	}
