<?php
	
	namespace sil21\VitrineBundle\Repository;
	
	/**
	 * MarqueRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class MarqueRepository extends \Doctrine\ORM\EntityRepository {
		/**
		 * @return array
		 */
		public function findAllOrderedByName() {
			return $this->getEntityManager()
				    ->createQuery( 'SELECT p FROM sil21VitrineBundle:Marque p ORDER BY p.name' )
				    ->getResult();
		}
	}
