<?php
	
	namespace sil21\VitrineBundle\Repository;
	
	use Doctrine\ORM\Query;
	
	/**
	 * ProductRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class ProductRepository extends \Doctrine\ORM\EntityRepository {
		/**
		 * @return array
		 */
		public function findAllOrderedByName() {
			return $this->getEntityManager()
				    ->createQuery( 'SELECT p FROM sil21VitrineBundle:Product p ORDER BY p.name ASC' )
				    ->getResult();
		}
		
		public function findAllBetterSales() {
			return $this->createQueryBuilder( 'p' )
				    ->select( 'IDENTITY(l.product)' )
				    ->addSelect( 'SUM(l.qte) AS cnt' )
				    ->from( 'sil21VitrineBundle:LigneCommande', 'l' )
				    ->groupBy( 'l.product'  )
				    ->orderBy( 'cnt' )
				    ->getQuery()
				    ->setMaxResults( 5 )
				    ->getResult();
			
			/*return $this->_em->createQuery( 'SELECT p, SUM(l.qte) AS cnt FROM sil21VitrineBundle:LigneCommande l JOIN l.product p GROUP BY l.product ORDER BY cnt DESC')
				->setMaxResults(5)
				->getResult();*/
		}
	}
