# ---------- IMPORT ----------

# -- Catégorie
sil21_categories:
    resource: "@sil21VitrineBundle/Resources/config/routing/category.yml"
    prefix: /category

# -- Produit
sil21_products:
    resource: "@sil21VitrineBundle/Resources/config/routing/product.yml"
    prefix: /product

# -- Produit
sil21_marques:
    resource: "@sil21VitrineBundle/Resources/config/routing/Marque.yml"
    prefix: /marque

# -- Commande
sil21_vitrine_commande:
        resource: "@sil21VitrineBundle/Resources/config/routing/Commande.yml"
        prefix:   /Commande

# -- Client
sil21_client:
    resource: "@sil21VitrineBundle/Resources/config/routing/client.yml"
    prefix:   /client

# -- Panier
sil21_cart:
    resource: "@sil21VitrineBundle/Resources/config/routing/cart.yml"
    prefix: /cart
    options:
        expose: true


# ---------- PAGES ----------

sil21_vitrine_homepage:
    path:     /
    defaults: { _controller: sil21VitrineBundle:Default:index }

sil21_mention:
    path: /mentions
    defaults: { _controller: sil21VitrineBundle:Default:mentions }
    


