# --------------------------------- #
# ----------- Brand ----------- #
# --------------------------------- #

# ---------- Application ----------

# -- Product by Brand
brand_articleByBrand:
    path:       /{id}/articles
    defaults: { _controller: "sil21VitrineBundle:Brand:articlesByBrand" , id: 0  }
    methods:  GET
    requirements:
        id:  \d+