# ------------------------------- #
# ------------ Cart------------ #
# ------------------------------- #

# ---------- Application ----------

# -- Content cart
sil21_cartContent:
     path:     /
     defaults: { _controller: sil21VitrineBundle:Cart:cartContent}

 # -- Validate cart
sil21_validateCart:
     path:       /validate
     defaults: { _controller: sil21VitrineBundle:Cart:validateCart}
     methods:  GET

# -- Add product
sil21_addArticle:
     path:     /addArticle/{id}/{qte}
     defaults: { _controller: sil21VitrineBundle:Cart:addArticle, qte: 1}
     requirements:
          id: \d+
          qte: \d+

# -- Change quantity of product
sil21_changeQuantityProduct:
    path:     /changeQuantityProduct/{id}/{qte}
    defaults: { _controller: sil21VitrineBundle:Cart:changeQutantity, qte: 1}
    methods:  [ GET, POST ]
    options:
            expose: true
    requirements:
        id: \d+
        qte: \d+

# -- Remove quantify of product in cart
sil21_removeQteProduct:
     path:     /removeOneProduct/{articleId}/{qte}
     defaults: { _controller: sil21VitrineBundle:Cart:removeQteProduct, articleId: 0, qte: 1}
     requirements:
          articleId: \d+
          qte: \d+

# -- Remove product form cart
sil21_removeProduct:
     path:     /removeProduct/{articleId}
     defaults: { _controller: sil21VitrineBundle:Cart:removeProduct, articleId: 0}
     requirements:
          articleId: \d+

# -- Empty the cart content
sil21_emptyCart:
     path:     /empty
     defaults: { _controller: sil21VitrineBundle:Cart:emptyCart}
