product_list:
    path:       /listUser
    defaults: { _controller: sil21VitrineBundle:Product:listAll}
    methods:  GET

product_index:
    path:     /
    defaults: { _controller: "sil21VitrineBundle:Product:index" }
    methods:  GET

product_show:
    path:     /{id}/show
    defaults: { _controller: "sil21VitrineBundle:Product:show" }
    methods:  GET

product_new:
    path:     /new
    defaults: { _controller: "sil21VitrineBundle:Product:new" }
    methods:  [GET, POST]

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "sil21VitrineBundle:Product:edit" }
    methods:  [GET, POST]

product_delete:
    path:     /{id}/delete
    defaults: { _controller: "sil21VitrineBundle:Product:delete" }
    methods:  DELETE
